# Generated by Django 3.0 on 2020-07-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0005_auto_20200714_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
