# Generated by Django 3.0 on 2020-07-15 05:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0006_auto_20200715_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
    ]
