# Generated by Django 3.0 on 2020-07-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0007_game_cells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
    ]
